service:
  name: ${env:NAME}
plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  timeout: 90
  runtime: nodejs14.x
  stage: ${env:STAGE}
  region: ${env:REGION}
  versionFunctions: false
  apiGateway:
    apiKeys:
      - rj-serverless-${env:STAGE}-api-key
    usagePlan:
      quota:
        limit: 1000000
        offset: 1
        period: MONTH
      throttle:
        burstLimit: 1000
        rateLimit: 1000
package:
  individually: true
custom:
  serverless-offline:
    apiKey: 'rj-local-key-1'
  urlPrefix: 'sls'
  webpack:
    includeModules: true
    excludeFiles: ./**/*.test.js
functions: ${file(./resources/lambda/functions.yml)}
resources:
  - ${file(./resources/config/iam.yml)}
